### ISSUE TITLE
Different Colors/Patterns [Question]

### ISSUE THREAD

**Issue by Zilarrezko** [atom/language-todo#19]
Is it possible to specify different colors for specific keywords? I know how to change the keywords, though I am unsure where it's grabbing the colors from and how I would give certain ones certain colors.

I do have my own syntax theme, and already have colors set up for them, if that helps point me in the right direction. 

Thanks in advance.

**Comment by lee-dohm** [comment]
The scope for the keyword itself is `storage.type.class.keyword` where `keyword` is the lowercased version of the keyword, i.e. TODO, HACK, FIXME, etc. Most syntax themes will color this differently than comments, but if you want to give each keyword a different color ... then all you have to do is add a style for each keyword in your syntax theme:

```less
.storage.type.class.todo {
  color: green;
}

.storage.type.class.fixme {
  color: yellow;
}

.storage.type.class.hack {
  color: red;
}
```
